### PR TITLE
Update rulesreference.html.twig

### PR DESCRIPTION
**Pull request by drawntotheflame**
adding first 8 points from FAQ.

### CODE REVIEW

**Comment by drawntotheflame** [comment]
no need to merge yet, @Kamalisk - I'll do more soon.

**Comment by drawntotheflame** [comment]
Ok this has all of 'game play' now. I have 'card ability interpretation' left to do.

**Comment by drawntotheflame** [comment]
Hi @Kamalisk , I've finished everything I want to do now. I think this can merge. Do you have a style for color:blue on the site? FAQ entries are marked with that. Thanks.

**Comment by Kamalisk** [comment]
thats fine for now.

**Pull request merged**
