### PR TITLE
Fix OCTGN XML export

### PR DESCRIPTION
**Pull request by rushl**
This fixes several elements for compatibility with the OCTGN module. It does not fix the investigator card. With this patch, you can import the deck into the OCTGN deck builder, add the actual investigator card, save and play.

### CODE REVIEW

**Comment by Kamalisk** [comment]
It may be how octgn works but that isnt how arkhamdb works. There is no type of card called "weakness", so there needs to be a section on enemy and treachery for those card types. Also some weaknesses are assets so will end up in those sections. 

It requires more effort to fix those changes, I am unsure why ocgtn needs a weakness section anyway, everything should just be sorted by card type (not sure why it needs that format either but seems to be how things are done)

**Comment by rushl** [comment]
Ah, ok. That file looked like a view to me, so I expected that it could be changed without an issue. So, just to be clear, everything else in the change is workable except for the weakness one?

**Comment by Kamalisk** [comment]
Well what you changed will work, but that will just put treachery cards into the weakness section. Not enemies or assets.

**Comment by rushl** [comment]
Now I see what you're saying. Then I need to move the Enemy iterator into the Weakness section as well.

**Comment by Kamalisk** [comment]
Yes but then the Necronomicon will still be in the asset section. I don't see the point of having a weakness section in the file at all. 

I would have a "deck" section, and if it is purely cosmetic, have a section for each card type.

**Comment by rushl** [comment]
True, it's not a perfect solution. Since Assets naturally occur in a player deck, but Enemies and Treacheries don't, they get filed under Weakness. As far as I know, the only time the section a card appears under is used is when a deck is loaded into the OCTGN deck builder. However, if a player is exporting a deck from arkhamdb, they are really wanting to skip the OCTGN deck builder. The problem is that when opening a deck - even to play I think - the deck's sections must match those defined in OCTGN,

**Comment by Kamalisk** [comment]
Ok, I feel like the better solution is to have an enemy and treachery section (as those basically naturally occur in player decks more often than not). If we move weaknesses out of the normal player cards, then we need to move them all, rather than lump the enemy/treachery cards into it.

**Comment by rushl** [comment]
Well, the inherit design of OCTGN doesn't provide the same level of flexibility that you can get when you are able to control the entire layout. OCTGN's ability to place cards in logical orders is locked to the deck sections. Whereas on arkhamdb, you can separate "player" cards from "weakness" cards required by the rules. In fact, you divide the screen into halves - where "player" cards go on top, and "weakness" cards (and other required cards) go on the bottom. OCTGN doesn't give that level of control. Thus the divisions of Asset, Event, and Skill, with Investigator and Weakness to round things out. When building a deck in OCTGN, that arrangement allows a player to organize cards in nearly the same manner as is possible on arkhamdb.

Dividing the Weakness section into Enemy, Treachery (and perhaps "Bad" Asset) would make things more confusing when deckbuilding, since all the deck sections are visible in a list of possible locations to place cards. It's natural for a player to assign the weakness card to the Weakness section, and they generally don't want to be so detailed as to determine if this weakness is an Enemy weakness, then sort it into that box. When you're handling the sorting programatically though, it's fine (and probably required) to keep that level of detail. 

Essentially, the deck sections for OCGTN are attempting to replicate the same sorting mechanism as used on arkahmdb - separating player chosen cards from required cards. The difference is having to work within OCTGN's limitations for visually arranging the data. It might make things a bit awkward when lining up arkhamdb's categories with OCTGN's sections, but I think for users building decks in OCTGN, the current arrangement is best.

Ideally, it would be best if all the player chosen cards were sorted into Asset, Event, and Skill sections on export, required cards that aren't Weaknesses would go into the Investigator section, and Weakness cards went into their own section. I understand that it might not be possible to get that level of detail however. My goal here was to get the export feature to function at a level sufficient to be usable. Once a deck is loaded for play, the deck sections are no longer very relevant, However, the deck won't load at all unless the sections match.

**Comment by Kamalisk** [comment]
Will merge this, but I plan to fix this properly and put all weaknesses into the the weakness section. Looking at the octgn deck format, I don't see any reason to split card types up and not just have a "deck" but if that is how they do it, then that is how I will implement it.

**Pull request merged**
