### PR TITLE
First Work about I18N: DB I18Ned and site configuration with subdomains

### PR DESCRIPTION
**Pull request by fafranco82**
Hello,

this is the first part of the I18N process: setup the app and the db for I18Ned data:

* DoctrineExtensions Translatable configuration
* Custom repositories for all translatable entities
* New command `app:import:trans` to import translations from json data repository
* Routes I18Ned with subdomains, so, to view the list of cards in the core set in Spanish, you go to `https://es.arkhamdb.com/set/core`
* Locale switcher added on the navbar, after user dropdown.

For the routing by subdomain, you will need to add a line in your `parameters.yml` file, just below `website_name`:

`website_url: arkhamdb.com`

`website_url: ~`  was added to `parameters.yml.dist`, too.

### CODE REVIEW

**Comment by Kamalisk** [comment]
So how does this all work with data that is missing from the translation? Or additional fields/tables which I add? 
You replaced some of the card finds by a function, but I am fairly sure there are a lot of those all over the code, would they ignore the translations? I presume search right now will just search the english?

**Comment by fafranco82** [comment]
Only card data are translated by the moment. This is only the first piece of work, to have all cards translated, at least in deckbuilder and card listings (although part of the interface will remain in English... by now). The new functions is to use a doctrine query hint that do all the work for bringing translations whitin non-translatable data. The only new table is `ext_translations`, created by the i18n plugin, so a simple `doctrine:schema:update --force` command would be needed. If all of this are ok, I will continue with the I18N work, translating the interface and so on, like thronesdb.com is right now ;)

**Comment by Kamalisk** [comment]
So I mostly have this working, but since i had to update doctrine and fix a few issues, it still needs some testing and will need down time to make changes to the live site.

**Comment by Kamalisk** [comment]
The other question I have is, the upgrade system and calculating XP involves card name matching, I am guessing this might be an issue if one of the cards is in spanish and the other card is not translated yet.

**Comment by fafranco82** [comment]
I haven't thought on that... Yes, if an upgraded version of a translated card is not yet translated will be an issue... I think we can risk on this, because no many users will be using the spanish language at first, and change the XP calculator to a more language-independent system, for example using card codes and a relationship between a card and its upgraded versions... It would be more work, but there is no rush. And the spanish translations will be available as soon as the spanish publisher release them, usually only a day after US release.

**Comment by Kamalisk** [comment]
well the best solution would be to put the english card name in all entries regardless as a upgrade data. No need to link them then, would rather not have to manually look up card codes to add links when new cards are released if it can be magic.

**Comment by fafranco82** [comment]
Yes, it's a good solution, the only problem would be you will need two different queries to get the translated and untranslated names.

**Comment by Kamalisk** [comment]
nah, all queries would return the English name as a "real_name" column or something. So the English names would just be duplicated in the data.

**Comment by Kamalisk** [comment]
So I merged this into live, however I have disabled the actual translation option, so it means after more testing I can try adding spanish to live. With most of the changes live, should be easy to turn it on when its ready.

**Comment by fafranco82** [comment]
How did testing go? I've update json data to the last pack.

**Comment by Kamalisk** [comment]
I still have to add support for making sure upgrading cards works properly, otherwise it seems to be running fine with the changes.

**Pull request merged**
